apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kind-app-deployment
  template:
    metadata:
      labels:
        app: kind-app-deployment
    spec:
      containers:
        - name: kind-app-deployment
          image: maiempire/kind-app:latest
          ports:
          - containerPort: 3000
          name: kind-app-deployment