
apiVersion: v1
kind: Service
metadata:
  name: kind-app-service
spec:
  type: LoadBalancer
  selector:
    app: kind-app-deployment
  ports:
  - name: kind-app-deployment
    protocol: TCP
    port: 3000
    targetPort: 3000 

